spring.application.name=spring-security-starter

server.port=8082

#mysql stuff
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/security_starter
spring.datasource.username=root
spring.datasource.password=veda1234
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


#devtools stuff (or just use ctrl+f9)
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

#jwt
jwt.secret=R2dF5vH9tYq3JzLpX1C8bWmNsTr0vPq4XkA7Uw6dE9oKjMnQpakdflajdfiajjsfalksdlfkajdfdncakljdfaslna
jwt.expirationMs=3600000
